baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'
version = '0.0.1'

[pagination]
  pagerSize = 10

[params]
  [params.colors]
    # Light Mode Colors
    primary = "#386641"
    secondary = "#6a994e"
    accent = "#a7c957"
    background = "#f2e8cf"
    highlight = "#bc4749"
    
    # Dark Mode Color Overrides
    [params.colors.dark]
      primary = "#7fc97f"
      secondary = "#9ed98e"
      accent = "#c5e8a1"

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'Tools'
    pageRef = '/tools'
    weight = 30

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = '0.152.0'
